### ISSUE TITLE
doc fix: pts is first result, fit line is second:

### ISSUE THREAD

**Issue by jbclements** [florence/plot-bestfit#1]
The documentation suggests that the first result of the graph/linear function is a renderer for the best-fit line, and that the second one is the raw points. In fact, it appears that the reverse is true. To see this, run this code (adapted from the example code):

``` Racket
#lang racket

(require plot
         bestfit
         math/flonum)

(define (3x^2 x) (* 3.0 (expt x 2.0)))
(define (add-error y) (+ y (* y (/ (- (random 4) 2) 10.0))))
(define exact (function 3x^2 #:label "exact" #:color "blue"))
(define-values (fit pts _)
   (graph/power (build-list 10 (compose fl add1))
                 (build-list 10 (compose 3x^2 fl add1))))
(plot (list fit))
```

**Comment by florence** [comment]
Fixed by c1fd0f204724b0a2b43eab3a0d1a77032d96bddd. Thanks!
